version: 2.1
orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          name: Install dependencies in virtual environment
          command: |
            virtualenv ~/venv
            source ~/venv/bin/activate
            pip install -r requirements.txt
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "~/venv"
      - run:
          name: Run unit tests
          command: |
            source ~/venv/bin/activate
            cp sample_shavar_list_creation.ini shavar_list_creation.ini
            mkdir test-results
            python -m pytest -v --junitxml=test-results/junit.xml
      - store_test_results:
              path: test-results
